from coffeehr.pipeline.interface import Pipeline

pipeline = Pipeline(
    name="Activities",
    get_options=("POST", "SYN_EL_QuaTrinhLamViec"),
    transform=lambda rows: [
        {
            "MaNhanVien": row.get("MaNhanVien"),
            "HoVaTen": row.get("HoVaTen"),
            "NgayQuyetDinh": row.get("NgayQuyetDinh"),
            "NgayHieuLuc": row.get("NgayHieuLuc"),
            "MaPBErpCu": row.get("MaPBErpCu"),
            "MaPBCu": row.get("MaPBCu"),
            "TenPBCu": row.get("TenPBCu"),
            "MaPBErpMoi": row.get("MaPBErpMoi"),
            "MaPBMoi": row.get("MaPBMoi"),
            "TenPBMoi": row.get("TenPBMoi"),
            "MaChucVuCu": row.get("MaChucVuCu"),
            "ChucVuCu": row.get("ChucVuCu"),
            "maChucVuMoi": row.get("maChucVuMoi"),
            "ChucVuMoi": row.get("ChucVuMoi"),
            "MaChucDanhCu": row.get("MaChucDanhCu"),
            "ChucDanhCu": row.get("ChucDanhCu"),
            "MaChucDanhMoi": row.get("MaChucDanhMoi"),
            "ChucDanhMoi": row.get("ChucDanhMoi"),
            "TenLyDoChuyenCanBo": row.get("TenLyDoChuyenCanBo"),
            "GhiChu": row.get("GhiChu"),
        }
        for row in rows
    ],
    schema=[
        {"name": "MaNhanVien", "type": "STRING"},
        {"name": "HoVaTen", "type": "STRING"},
        {"name": "NgayQuyetDinh", "type": "TIMESTAMP"},
        {"name": "NgayHieuLuc", "type": "TIMESTAMP"},
        {"name": "MaPBErpCu", "type": "STRING"},
        {"name": "MaPBCu", "type": "NUMERIC"},
        {"name": "TenPBCu", "type": "STRING"},
        {"name": "MaPBErpMoi", "type": "STRING"},
        {"name": "MaPBMoi", "type": "NUMERIC"},
        {"name": "TenPBMoi", "type": "STRING"},
        {"name": "MaChucVuCu", "type": "NUMERIC"},
        {"name": "ChucVuCu", "type": "STRING"},
        {"name": "maChucVuMoi", "type": "NUMERIC"},
        {"name": "ChucVuMoi", "type": "STRING"},
        {"name": "MaChucDanhCu", "type": "NUMERIC"},
        {"name": "ChucDanhCu", "type": "STRING"},
        {"name": "MaChucDanhMoi", "type": "NUMERIC"},
        {"name": "ChucDanhMoi", "type": "STRING"},
        {"name": "TenLyDoChuyenCanBo", "type": "STRING"},
        {"name": "GhiChu", "type": "STRING"},
    ],
)
